module.exports = {

    SUBSCRIPTION_CREATED:
        'SUBSCRIPTION_CREATED',

    SUBSCRIPTION_CANCELLED:
        'SUBSCRIPTION_CANCELLED',

    SUBSCRIPTION_EXPIRED:
        'SUBSCRIPTION_EXPIRED',

    PAYMENT_SUCCESS:
        'PAYMENT_SUCCESS',

    PAYMENT_FAILED:
        'PAYMENT_FAILED'
};