module.exports = {

    JOB_CREATED:
        'JOB_CREATED',

    JOB_UPDATED:
        'JOB_UPDATED',

    JOB_DELETED:
        'JOB_DELETED',

    APPLICATION_SUBMITTED:
        'APPLICATION_SUBMITTED',

    APPLICATION_ACCEPTED:
        'APPLICATION_ACCEPTED',

    APPLICATION_REJECTED:
        'APPLICATION_REJECTED',

    APPLICATION_REVIEWED:
        'APPLICATION_REVIEWED'
};